{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "eshop.fullname" . }}-basket-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: basket-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "eshop.fullname" . }}-basket-api
  minReplicas: {{ .Values.autoscaling.basketApi.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.basketApi.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.basketApi.targetCPUUtilizationPercentage }}
  {{- if .Values.autoscaling.basketApi.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.basketApi.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
