{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: amqp
    protocol: TCP
  - name: management
    port: 15672
    targetPort: management
    protocol: TCP
  selector:
    {{- include "eshop.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}
